# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: ./
date_format: "ordinal"
title: 太极与编程
subtitle: "人生很长,慢慢经历"
description: "老骥(jì)伏枥(lì)，志在千里"
keywords: 随手记, perfectstorm
timezone: Asia/Shanghai
encoding: "utf-8"
# side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: perfectstorm88
organization: 太极与编程，两者皆爱好；前者来养生，后者去糊口；若想常青在，每日勤练习；一两遍套路，百十行代码。
organization_url: 
github_username: 
location: 
email: perfectstorm88@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

#   -
#     href: /wiki/
#     label: 维基

#   -
#     href: /links/
#     label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10 # 分页功能
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: perfectstorm88/perfectstorm88.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: perfectstorm88
    repo: blog-comments
    oauth:
        client_id: 1ca5816e0ea00e27e45a
        client_secret: b3db787aef90fac9c8a1c585970094399135ebc3
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: perfectstorm88
    repo: blog-comments
    clientID: 1ca5816e0ea00e27e45a
    clientSecret: b3db787aef90fac9c8a1c585970094399135ebc3
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 20

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
